
#  SOCIAL MEDIA CYBERBULLYING DETECTION

Presented by:
1. Stella Kiarie

2. Kumati Dapash

3. Morvine Otieno

4. Doris Mutie

# 1. BUSINESS UNDERSTANDING

## 1.1 Overview   
The kenyan digital landscape is one of the most vibrant in Africa, driven by a huge population of young, tech savvy and a high rate of mobile internet usage.  The major platforms for social engagement, entertainment and business being FaceBook, YouTube, TikTok and X(formerly Twitter).  Content creators, artists, vloggers and commentators commanding millions of comments daily.   
Due to the anonymity and viral nature of these social media platforms, there is a developing culture if cyberbullying and online hostility. Unlike other Western countexts where comments fall under well known languages, Kenyan  comment section is characterized by code -switching between Kiswahili, English and Sheng. Sheng is mostly being used to deliver insults or to "roast" individuals in the online space.   

The current global cyberbulling moderation tools are primarily built in well-known languages like English, French, and a little bit of Swahili.  Following the Kenyan linguistic complexity, there moderation tools fail to capture harmful sheng Phrases which leave kenyan content creators, public figures and online users vulnerable to online harrassmenr which in turn results to severe mental issues, reputation damages, suicidal ideation and digital exclusion.    

Social media connects us, entertains us but sometimes it destroys us. Remember behind every trending post or hashtag, there is a real person with real feelings.

## 1.2  Problem Statement

There is a significant gap in the ability to automate systems that can detect and moderate cyberbulling within the linguistic Kenyan context.  
Comments from Kenyan social media posts are based on sheng or code switching context which often bypass the existing moderation tools. The linguistic nuances of toxic content remain online, fueling a hostile digital environment. Content creators and brands are unable to moderate thousands of multilingual comments in real time, resulting in a toxic feedback loop that damages engagement and mental well-being.

## 1.3 Challenges

1. Linguistic Fluidity: Sheng is not standardized and a word might differ in meaning in different locations.
2. Code-mixed content: mixing English, swahili and sheng in one comment often confuse the existing NLP models
3. High Volume: Kenyan social media and digital space generate thousands of comments within hours which limits human moderation.
4. Contexual Sarcasm: While sheng is being used, deep contexual understanding is required to classfy comments whether "bullying", "hatespeech" rather than "Humor/Irony/Sarcism "
5. Data Scarcity: There is no publicly available high quality datasets for sheng specifically labelled for toxicity

## 1.3  Proposed Solution

We propose building an adavanced multilingual NLP classification system specifically tuned for the Kenyan linguistic landscape. A structured annotation through label studio  for human annotation to ensure conssistent and high quality annotation of kenyan social media comments.  
Each commenyt presented to the annotator will be labelled through four sequential steps:
1. Language Identification
2. Sentiment Classification
3. Major Category Classification
4. subcategory Classification  
This hierachical labeling will help analyze bothe the general and detailed information about the social media text

1. Language Identification: identify the primary language used in the comment 
The major language options include:   
  
        1. English
        2. Swahili
        3. Sheng
        4. Mixed (Code-switching)
        5. Plain Emoji

2. Sentiment Annotation : After identifying the language, the annotators will label the sentiment expessed in the comment.  
The sentiment categories include: 

            1. Negative
            2. Positve
            3. Neutral   
Help understand the emotional tone of the message to detect harmful and constructive communications.

3. Major Category Classification : classify the comment into a main category that represents the overall nature of the message.   
The major categories include:

        1. Constructive Criticism
        2. Offensive Content
        3. Cyberbullying
        4. Hate Speech
        5. Irony/Sarcasm
        6. Misinformation
        7. Other

4. Subategory Classification: each major category is linked to specific subcategories. 
### Subcategories Used in Data Annotation

### Subcategories by Major Category

| Constructive Criticism | Offensive | Cyberbullying | Hate Speech | Irony/Sarcasm | Misinformation | Others |
|---|---|---|---|---|---|---|
| [CC] Performance-based | [Offensive] Sex-based | [Bullying] Body shaming | [Hate Speech] Gender based | [Irony] Mock compliment | [Misinfo] Fabricated Content (Fake News) | [Other] Spam |
| [CC] Corrective clarification | [Offensive] Vulgar language (Matusi) | [Bullying] Direct Insult | [Hate Speech] Political | [Irony] Mock Laughter | [Misinfo] Misleading/Contextual Deception | [Other] General Others |
| [CC] Decision-criticism | [Offensive] Non-personal | [Bullying] Threats | [Hate Speech] Ethical/racial group (Tribalism) | [Irony] Rhetorical Question | [Misinfo] Parody | [Other] General Inquiry |
| [CC] Genuine Praise |  | [Bullying] Humiliation | [Hate Speech] Disability | [Irony] Hyperbolic understatement |  |  |
| [CC] Supportive Speech |  | [Bullying] Exclusion tactics |  |  |  |  |
| [CC] Genuine feedback |  | [Bullying] Sexual harassment |  |  |  |  |
|  |  | [Bullying] Trolling |  |  |  |  |
|  |  | [Bullying] Defamation |  |  |  |  |

## 1.5 Objectives

The goal is to develop a robust ML model that identifies and flags cyberbullying in Sheng, Swahili, and English with high accuracy. 

•	Scrape and curate specialized datasets of more than 10,000 comments from Kenyan YouTube vlogs.  

•	Use human annotators (Fluent Sheng speakers) to create high-quality labelled datasets

•	Evaluating the model performance using F1-score, ensuring the model handles imbalanced data where bullying is less frequent than neutral comments. 

•	Build a prototype API or Dashboard that content creators can use to clean their comment sections automatically.

## 1.6 Success Criteria 
This project will be considered successful if:  

•	The model achieves an F1-Score of 75% or higher across the cyberbullying and hate speech categories. 

•	The system successfully identifies Sheng-specific insults that standard English filters miss.

# DATA UNDERSTANDING

## 2.1 Overview

To solve the problem identified in this project, we leveraged data from YoutubeTube comments from various Kenyan videos. The data will be scraped from YouTube using the YouTube Data API V3, an official and legal way of accessing public YouTube data for analysis. The project leverage the google-api-python-client interface with the comment Threads resource.   
The Scripts maps the raw JSON responses from YouTube and converts them into Pandas dataframe  
The data contains the following columns:  

•	Author: the public name of the commenter  
•	Text: raw comment content in plain text  
•	Likes: engagement metric  
•	Published at: Timestamp of the post.

Through this strategy, we managed to scrap  over 10,000 comments from Kenyan Youtube Content.

## 2.2 Labelling

### HUMAN DATA LABELLING AND ANNOTATION(Label Studio)

As compared to automated labeling methods, human annotators are better to interprate the nuances in the comments. 

Human annotation ensure accurate detection of harmful content in categories such as Cyberbullying, hate speech, offensive language and Sarcasm . These categories require human judgement because the meaning often depends on context and intention.   
* Human labeling helps ensure:  
* Correct classification of comments  
* Reliable sentiment detection  
* Consistent labeling across categories  
* High-quality training data for the NLP model.

## 2.3 Data Quality issues

Major data quality issues during the annotation process include;
1. A significant amount of data use non standard english hence annotator needs a local Kenyan Slang understanding to accurately identify the segments
2. class imbalance: Categories such as Contructive critism and Irony appear way more than other .
3. Certain names appear in toxic comments highlihting a need for annymization(masking). In data preparation to prevent the model from learninf "name_based" bias.

## Data Loading and Inspection

In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))
 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## Import Class Modules 
from Data_prep.loader import DataLoader
from Data_prep.eda import EDA

### Loading Dataset in a Dataframe

In [2]:
loader=DataLoader('final_data.csv')
data= loader.load_data()
data.head()

✅ Dataset loaded successfully from final_data.csv

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,annotation_id,annotator,author,category,clean_text,confidence_score,created_at,id,language,lead_time,likes,predicted_label,published_at,sentiment,subcategory,text,updated_at
0,0,NaN,5028,3011,1,@Annemimi234,Irony/Sarcasm,Napenda hii couple but hapo kwa 29yrs nimekata...,0.604895,2026-02-24T19:06:10.770015Z,10057,Mixed (Code-switching),224.696,10,neutral or positive,2025-07-28T16:36:04Z,Positive,[Irony] Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...,2026-02-24T19:06:10.770015Z
1,1,NaN,5029,3012,1,@MKLMNMKLMNMKLMN,Others,rada zako wasingam,0.291550,2026-02-24T19:08:59.913717Z,10058,Sheng,90.467,0,neutral or positive,2025-07-28T16:35:44Z,Neutral,[Other] General Others,rada zako wasingam,2026-02-24T19:08:59.913717Z
2,2,NaN,5030,3013,1,@raphaelmutinda8214,Constructive Criticism,Izo chwom mbaya ndio zetuu face_with_tears_of_...,0.623743,2026-02-24T19:10:09.116244Z,10059,Sheng,67.516,0,offensive language,2025-07-28T16:35:12Z,Positive,[CC] Genuine Praise,Izo chwom mbaya ndio zetuu😂😂,2026-02-24T19:10:09.116244Z
3,3,NaN,5031,3014,1,@rhinoriders6060,Constructive Criticism,Nka shy grinning_face_with_sweat,0.407087,2026-02-24T19:11:05.157793Z,10060,Mixed (Code-switching),53.456,0,neutral or positive,2025-07-28T16:35:07Z,Positive,[CC] Genuine Praise,Nka shy😅,2026-02-24T19:11:05.157793Z
4,4,NaN,5032,3015,1,@wanjawakariuki9079,Constructive Criticism,Ata kama ni dooh kuna shida zingine siwezi taka,0.627657,2026-02-24T19:18:26.750854Z,10061,Sheng,70.046,1,neutral or positive,2025-07-28T16:34:43Z,Neutral,[CC] Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka,2026-02-24T19:18:26.750854Z

### Dropping Colums

In [3]:
columns_to_drop= ["Unnamed: 0","Unnamed: 0.2","Unnamed: 0.1","annotation_id","annotator",
                  "author","clean_text","confidence_score","created_at","id",
                  "lead_time","predicted_label","updated_at"]
data=loader.drop_irrelevant_columns(columns_to_drop)

✅ Dropped columns: ['Unnamed: 0', 'Unnamed: 0.2', 'Unnamed: 0.1', 'annotation_id', 'annotator', 'author', 'clean_text', 'confidence_score', 'created_at', 'id', 'lead_time', 'predicted_label', 'updated_at']
New shape: (6031, 8)

In [4]:
data.columns

Index(['Unnamed: 0.1.1', 'category', 'language', 'likes', 'published_at',
       'sentiment', 'subcategory', 'text'],
      dtype='object')

### Checking Info

In [5]:
loader.check_info()

📊 DATA INFO
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6031 entries, 0 to 6030
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0.1.1  6031 non-null   int64
 1   category        6031 non-null   object
 2   language        6031 non-null   object
 3   likes           6031 non-null   int64
 4   published_at    6031 non-null   object
 5   sentiment       6031 non-null   object
 6   subcategory     6013 non-null   object
 7   text            6030 non-null   object
dtypes: int64(2), object(6)
memory usage: 377.1+ KB
None

Shape: (6031, 8)

## Checking for missing Values

In [6]:
loader.check_missing_values()

🔎 MISSING VALUES
==================================================
Unnamed: 0.1.1     0
category           0
language           0
likes              0
published_at       0
sentiment          0
subcategory       18
text               1
dtype: int64

Unnamed: 0.1.1     0
category           0
language           0
likes              0
published_at       0
sentiment          0
subcategory       18
text               1
dtype: int64

### Drop missing values

In [7]:
loader.drop_missing_values()

✅ Dropped 19 rows with missing values.
New shape: (6012, 8)

,Unnamed: 0.1.1,category,language,likes,published_at,sentiment,subcategory,text
0,5028,Irony/Sarcasm,Mixed (Code-switching),10,2025-07-28T16:36:04Z,Positive,[Irony] Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...
1,5029,Others,Sheng,0,2025-07-28T16:35:44Z,Neutral,[Other] General Others,rada zako wasingam
2,5030,Constructive Criticism,Sheng,0,2025-07-28T16:35:12Z,Positive,[CC] Genuine Praise,Izo chwom mbaya ndio zetuu😂😂
3,5031,Constructive Criticism,Mixed (Code-switching),0,2025-07-28T16:35:07Z,Positive,[CC] Genuine Praise,Nka shy😅
4,5032,Constructive Criticism,Sheng,1,2025-07-28T16:34:43Z,Neutral,[CC] Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka
...,...,...,...,...,...,...,...,...
6026,5023,Irony/Sarcasm,Sheng,0,2025-07-28T16:38:05Z,Negative,[Irony] Mock compliment,Wenye hawajui venye street hu-run mnafloat tu😂...
6027,5024,Constructive Criticism,English,0,2025-07-28T16:37:50Z,Positive,[CC] Genuine feedback,I can answer that question more further😂😂😂😂😂😂
6028,5025,Constructive Criticism,English,2,2025-07-28T16:37:39Z,Positive,[CC] Genuine Praise,wedding of the year ❤❤
6029,5026,Constructive Criticism,Sheng,1,2025-07-28T16:37:19Z,Neutral,[CC] Supportive Speech,"Hiyo wedding nayo , episode 2000 and I can’t g..."
6030,5027,Constructive Criticism,English,7,2025-07-28T16:36:14Z,Positive,[CC] Genuine feedback,"I like the suit Obinna is wearing. Well, the c..."

In [8]:
loader.check_shape()

📐 Current Shape: (6012, 8)

(6012, 8)

### Check for Duplicates

In [9]:
loader.check_duplicates()

🔁 Duplicate rows: 0

0

In [10]:
loader.drop_duplicates()

✅ No duplicate rows found.

,Unnamed: 0.1.1,category,language,likes,published_at,sentiment,subcategory,text
0,5028,Irony/Sarcasm,Mixed (Code-switching),10,2025-07-28T16:36:04Z,Positive,[Irony] Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...
1,5029,Others,Sheng,0,2025-07-28T16:35:44Z,Neutral,[Other] General Others,rada zako wasingam
2,5030,Constructive Criticism,Sheng,0,2025-07-28T16:35:12Z,Positive,[CC] Genuine Praise,Izo chwom mbaya ndio zetuu😂😂
3,5031,Constructive Criticism,Mixed (Code-switching),0,2025-07-28T16:35:07Z,Positive,[CC] Genuine Praise,Nka shy😅
4,5032,Constructive Criticism,Sheng,1,2025-07-28T16:34:43Z,Neutral,[CC] Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka
...,...,...,...,...,...,...,...,...
6026,5023,Irony/Sarcasm,Sheng,0,2025-07-28T16:38:05Z,Negative,[Irony] Mock compliment,Wenye hawajui venye street hu-run mnafloat tu😂...
6027,5024,Constructive Criticism,English,0,2025-07-28T16:37:50Z,Positive,[CC] Genuine feedback,I can answer that question more further😂😂😂😂😂😂
6028,5025,Constructive Criticism,English,2,2025-07-28T16:37:39Z,Positive,[CC] Genuine Praise,wedding of the year ❤❤
6029,5026,Constructive Criticism,Sheng,1,2025-07-28T16:37:19Z,Neutral,[CC] Supportive Speech,"Hiyo wedding nayo , episode 2000 and I can’t g..."
6030,5027,Constructive Criticism,English,7,2025-07-28T16:36:14Z,Positive,[CC] Genuine feedback,"I like the suit Obinna is wearing. Well, the c..."

### Standardizing columnns and Column Names

In [11]:
loader.standardize_column_names()

✅ Column names standardized.
New columns: ['unnamed_011', 'category', 'language', 'likes', 'published_at', 'sentiment', 'subcategory', 'text']

,unnamed_011,category,language,likes,published_at,sentiment,subcategory,text
0,5028,Irony/Sarcasm,Mixed (Code-switching),10,2025-07-28T16:36:04Z,Positive,[Irony] Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...
1,5029,Others,Sheng,0,2025-07-28T16:35:44Z,Neutral,[Other] General Others,rada zako wasingam
2,5030,Constructive Criticism,Sheng,0,2025-07-28T16:35:12Z,Positive,[CC] Genuine Praise,Izo chwom mbaya ndio zetuu😂😂
3,5031,Constructive Criticism,Mixed (Code-switching),0,2025-07-28T16:35:07Z,Positive,[CC] Genuine Praise,Nka shy😅
4,5032,Constructive Criticism,Sheng,1,2025-07-28T16:34:43Z,Neutral,[CC] Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka
...,...,...,...,...,...,...,...,...
6026,5023,Irony/Sarcasm,Sheng,0,2025-07-28T16:38:05Z,Negative,[Irony] Mock compliment,Wenye hawajui venye street hu-run mnafloat tu😂...
6027,5024,Constructive Criticism,English,0,2025-07-28T16:37:50Z,Positive,[CC] Genuine feedback,I can answer that question more further😂😂😂😂😂😂
6028,5025,Constructive Criticism,English,2,2025-07-28T16:37:39Z,Positive,[CC] Genuine Praise,wedding of the year ❤❤
6029,5026,Constructive Criticism,Sheng,1,2025-07-28T16:37:19Z,Neutral,[CC] Supportive Speech,"Hiyo wedding nayo , episode 2000 and I can’t g..."
6030,5027,Constructive Criticism,English,7,2025-07-28T16:36:14Z,Positive,[CC] Genuine feedback,"I like the suit Obinna is wearing. Well, the c..."

In [12]:
loader.clean_subcategory()

✅ Cleaned 'subcategory' column.

,unnamed_011,category,language,likes,published_at,sentiment,subcategory,text
0,5028,Irony/Sarcasm,Mixed (Code-switching),10,2025-07-28T16:36:04Z,Positive,Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...
1,5029,Others,Sheng,0,2025-07-28T16:35:44Z,Neutral,General Others,rada zako wasingam
2,5030,Constructive Criticism,Sheng,0,2025-07-28T16:35:12Z,Positive,Genuine Praise,Izo chwom mbaya ndio zetuu😂😂
3,5031,Constructive Criticism,Mixed (Code-switching),0,2025-07-28T16:35:07Z,Positive,Genuine Praise,Nka shy😅
4,5032,Constructive Criticism,Sheng,1,2025-07-28T16:34:43Z,Neutral,Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka
...,...,...,...,...,...,...,...,...
6026,5023,Irony/Sarcasm,Sheng,0,2025-07-28T16:38:05Z,Negative,Mock compliment,Wenye hawajui venye street hu-run mnafloat tu😂...
6027,5024,Constructive Criticism,English,0,2025-07-28T16:37:50Z,Positive,Genuine feedback,I can answer that question more further😂😂😂😂😂😂
6028,5025,Constructive Criticism,English,2,2025-07-28T16:37:39Z,Positive,Genuine Praise,wedding of the year ❤❤
6029,5026,Constructive Criticism,Sheng,1,2025-07-28T16:37:19Z,Neutral,Supportive Speech,"Hiyo wedding nayo , episode 2000 and I can’t g..."
6030,5027,Constructive Criticism,English,7,2025-07-28T16:36:14Z,Positive,Genuine feedback,"I like the suit Obinna is wearing. Well, the c..."

In [13]:
loader.clean_language_column()

✅ Cleaned 'language' column.

,unnamed_011,category,language,likes,published_at,sentiment,subcategory,text
0,5028,Irony/Sarcasm,Code Switching,10,2025-07-28T16:36:04Z,Positive,Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...
1,5029,Others,Sheng,0,2025-07-28T16:35:44Z,Neutral,General Others,rada zako wasingam
2,5030,Constructive Criticism,Sheng,0,2025-07-28T16:35:12Z,Positive,Genuine Praise,Izo chwom mbaya ndio zetuu😂😂
3,5031,Constructive Criticism,Code Switching,0,2025-07-28T16:35:07Z,Positive,Genuine Praise,Nka shy😅
4,5032,Constructive Criticism,Sheng,1,2025-07-28T16:34:43Z,Neutral,Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka
...,...,...,...,...,...,...,...,...
6026,5023,Irony/Sarcasm,Sheng,0,2025-07-28T16:38:05Z,Negative,Mock compliment,Wenye hawajui venye street hu-run mnafloat tu😂...
6027,5024,Constructive Criticism,English,0,2025-07-28T16:37:50Z,Positive,Genuine feedback,I can answer that question more further😂😂😂😂😂😂
6028,5025,Constructive Criticism,English,2,2025-07-28T16:37:39Z,Positive,Genuine Praise,wedding of the year ❤❤
6029,5026,Constructive Criticism,Sheng,1,2025-07-28T16:37:19Z,Neutral,Supportive Speech,"Hiyo wedding nayo , episode 2000 and I can’t g..."
6030,5027,Constructive Criticism,English,7,2025-07-28T16:36:14Z,Positive,Genuine feedback,"I like the suit Obinna is wearing. Well, the c..."

# 📊 Exploratory Data Analysis (EDA)

## Introduction

This section explores the structure, distribution, and characteristics of the cyberbullying dataset before modeling.  
The goal is to understand patterns in categories, sentiment, text behavior, language usage, and posting activity.

In [14]:
eda = EDA(loader.data)

### A) Dataset Overview

The dataset overview examined the structure and quality of the data.  
This included checking the number of rows and columns, data types, column names, and missing values.  

This step ensured the dataset is clean, properly formatted, and ready for deeper exploratory analysis and modeling.

In [15]:

eda.dataset_overview()

📊 DATASET OVERVIEW
============================================================
Shape: (6012, 8)

Columns:
['unnamed_011', 'category', 'language', 'likes', 'published_at', 'sentiment', 'subcategory', 'text']

Data Types:
unnamed_011      int64
category        object
language        object
likes            int64
published_at    object
sentiment       object
subcategory     object
text            object
dtype: object

Missing Values:
unnamed_011     0
category        0
language        0
likes           0
published_at    0
sentiment       0
subcategory     0
text            0
dtype: int64

### B) Target Distribution Analysis

This analysis explored the distribution of posts across different cyberbullying categories and sentiment classes.  

Understanding class balance is important for machine learning, as imbalanced data may require resampling or class weighting.  
The sentiment distribution also provides insight into the overall emotional tone of the dataset.

In [16]:
eda.target_distribution("category")

Class Percentages:
Constructive Criticism    52.73
Others                    21.74
Cyberbullying             10.66
Irony/Sarcasm              8.53
Offensive                  4.62
Misinformation             1.10
Hate Speech                0.62
Name: category, dtype: float64

In [17]:
eda.target_distribution("sentiment")

Class Percentages:
Neutral     38.21
Positive    33.72
Negative    28.08
Name: sentiment, dtype: float64

### C) Subcategory Analysis

The subcategory analysis examined more detailed classifications of cyberbullying behavior.  

This helps identify dominant bullying patterns and determines whether fine-grained classification is feasible.  
It also highlights subcategories that may require balancing during model training.

In [18]:
eda.subcategory_analysis()

### D) Text Length Analysis

Text length analysis evaluated the distribution of post lengths in characters.  

This insight helps determine appropriate tokenization limits, sequence lengths for NLP models, and detection of unusually short or long posts that may affect model performance.

In [19]:
eda.text_length_analysis()

Text Length Summary:
count    6012.000000
mean       49.079508
std        49.551296
min         1.000000
25%        21.000000
50%        36.000000
75%        61.000000
max      1020.000000
Name: text_length, dtype: float64

### E) Language Distribution

The language distribution analysis identified the dominant languages used in the dataset.  

This is important for preprocessing decisions such as stopword removal, tokenization strategy, and determining whether multilingual modeling is required.

In [20]:
eda.language_insights()

Language Percentages:
Code Switching    38.59
English           24.07
Sheng             18.28
Swahili           16.53
Plain Emoji        2.53
Name: language, dtype: float64

### F) Peak Posting Time Analysis (Kenyan Time - EAT)

This analysis converted timestamps to Kenyan time (EAT - UTC+3) and examined hourly posting patterns.  

Identifying peak activity hours provides behavioral insights into when cyberbullying is most active and may support real-time moderation strategies.  
Weekend and weekday comparisons further contextualize user behavior.

In [21]:
eda.peak_posting_times("published_at")

🕒 Posting Activity by Hour
============================================================
0     478
1     179
2     100
3      77
4      63
5      48
6      62
7     100
8     186
9     218
10    230
11    289
12    281
13    308
14    225
15    219
16    237
17    218
18    222
19    365
20    454
21    490
22    396
23    567
Name: hour, dtype: int64

🔥 Peak Posting Hour:
23:00

📅 Weekend vs Weekday Activity
============================================================
is_weekend
False    4229
True     1783
Name: hour, dtype: int64

0     478
1     179
2     100
3      77
4      63
5      48
6      62
7     100
8     186
9     218
10    230
11    289
12    281
13    308
14    225
15    219
16    237
17    218
18    222
19    365
20    454
21    490
22    396
23    567
Name: hour, dtype: int64

### G) Key Findings Summary

The key findings section summarized major insights from the EDA process, including dominant categories, sentiment trends, language patterns, and average text length.  

These insights guide preprocessing decisions, feature engineering, and model development strategies for the cyberbullying detection system.

In [22]:
eda.key_findings()

🔎 KEY FINDINGS SUMMARY
============================================================
Total Samples: 6012

Top Category:
Constructive Criticism

Top Sentiment:
Neutral

Most Common Language:
Code Switching

Average Text Length: 49.08 characters

## PRE-PROCESSING

In [23]:
!pip install emoji
from Data_prep.preprocesssing import TextPreprocessor
preprocessor = TextPreprocessor()
final_df = preprocessor.transform(data, column="text")
final_df.head()

Requirement already satisfied: emoji in c:\users\lenovo\anaconda3\envs\learn-env\lib\site-packages (2.15.0)

,unnamed_011,category,language,likes,published_at,sentiment,subcategory,text,clean_text
0,5028,Irony/Sarcasm,Code Switching,10,2025-07-28T16:36:04Z,Positive,Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...,napenda hii couple but hapo kwa 29yrs nimekata...
1,5029,Others,Sheng,0,2025-07-28T16:35:44Z,Neutral,General Others,rada zako wasingam,rada zako wasingam
2,5030,Constructive Criticism,Sheng,0,2025-07-28T16:35:12Z,Positive,Genuine Praise,Izo chwom mbaya ndio zetuu😂😂,izo chwom mbaya ndio zetuu face_with_tears_of_...
3,5031,Constructive Criticism,Code Switching,0,2025-07-28T16:35:07Z,Positive,Genuine Praise,Nka shy😅,nka shy grinning_face_with_sweat
4,5032,Constructive Criticism,Sheng,1,2025-07-28T16:34:43Z,Neutral,Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka,ata kama ni dooh kuna shida zingine siwezi taka

## Feature Engineering

In [24]:
# Notebook cell
import sys
import os

# Add project root
sys.path.append(os.path.abspath(".."))  # adjust if notebook is inside Notebooks/
from Models.Feature_engineering import FeatureEngineer
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, f1_score, confusion_matrix

# Initialize Feature Engineer
fe = FeatureEngineer(
    test_size=0.2,
    random_state=42,
    max_word_features=8000,
    max_char_features=20000,
    scale_numeric=True
)

In [25]:
# Notebook cell
def merge_languages_dynamic(label):
    """
    Returns:
    - 'Mixed' if the text contains code-switching
    - Keeps original language if it's pure English, Swahili, or Sheng
    - 'Emoji' if plain emoji
    """
    if label == "Code Switching":
        return "Mixed"
    elif label == "Plain Emoji":
        return "Emoji"
    else:
        return label  # English, Swahili, Sheng stay as they are

# Apply to your dataframe
final_df["language_final"] = final_df["language"].apply(merge_languages_dynamic)

# Check distribution
print(final_df["language_final"].value_counts())

Mixed      2320
English    1447
Sheng      1099
Swahili     994
Emoji       152
Name: language_final, dtype: int64

In [26]:
X_train_text, X_test_text, y_train, y_test = fe.split(
    final_df["clean_text"],       # your preprocessed text
    final_df["language_final"]    # use the correct column name
)

In [27]:
X_train = fe.fit_transform(X_train_text)
X_test = fe.transform(X_test_text)

In [28]:
# Initialize model
lang_model = LinearSVC(class_weight="balanced", max_iter=30000)

# Train
lang_model.fit(X_train, y_train)

# Predict
y_pred = lang_model.predict(X_test)

# Evaluation
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Macro F1:", f1_score(y_test, y_pred, average="macro"))
print("Weighted F1:", f1_score(y_test, y_pred, average="weighted"))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

       Emoji       0.46      0.87      0.60        30
     English       0.66      0.72      0.69       290
       Mixed       0.55      0.50      0.52       464
       Sheng       0.52      0.46      0.49       220
     Swahili       0.38      0.42      0.40       199

    accuracy                           0.54      1203
   macro avg       0.52      0.59      0.54      1203
weighted avg       0.54      0.54      0.54      1203

Macro F1: 0.5411274117564095
Weighted F1: 0.5380850661277814
Confusion Matrix:
 [[ 26   0   3   0   1]
 [  9 210  46   9  16]
 [ 14  78 230  61  81]
 [  4  11  68 101  36]
 [  3  17  74  22  83]]

In [29]:
# Notebook cell
import sys
import os
sys.path.append(os.path.abspath(".."))

from Models.pipelines import LanguagePipeline, SentimentPipeline, CategoryPipeline, SubcategoryPipeline

# Example for language
lang_pipe = LanguagePipeline()
lang_pipe.train(final_df["clean_text"], final_df["language_final"])
print(lang_pipe.predict(["wewe that was unnecessary bana."]))
# Example for sentiment
sent_pipe = SentimentPipeline()
sent_pipe.train(final_df["clean_text"], final_df["sentiment"])
print(sent_pipe.predict(["I hate this so much!"]))

# You can do same for categories & subcategories
cat_pipe = CategoryPipeline()
cat_pipe.train(final_df["clean_text"], final_df["category"])
print(cat_pipe.predict(["You are so annoying 😡"]))

subcat_pipe = SubcategoryPipeline()
subcat_pipe.train(final_df["clean_text"], final_df["subcategory"])
print(subcat_pipe.predict(["You are so annoying 😡"]))

Classification Report:

              precision    recall  f1-score   support

       Emoji       0.41      0.86      0.56        22
     English       0.62      0.71      0.66       289
       Mixed       0.57      0.50      0.53       466
       Sheng       0.52      0.55      0.54       207
     Swahili       0.47      0.43      0.45       219

    accuracy                           0.55      1203
   macro avg       0.52      0.61      0.55      1203
weighted avg       0.55      0.55      0.55      1203

Weighted F1: 0.5489095683596098
Macro F1: 0.5475427257905305

Confusion Matrix:
 [[ 19   2   1   0   0]
 [  7 205  49  10  18]
 [ 10  95 231  62  68]
 [  5  12  53 114  23]
 [  5  15  72  32  95]]
['English']

Classification Report:

              precision    recall  f1-score   support

    Negative       0.48      0.54      0.51       340
     Neutral       0.51      0.51      0.51       489
    Positive       0.60      0.54      0.57       374

    accuracy                           0.53      1203
   macro avg       0.53      0.53      0.53      1203
weighted avg       0.53      0.53      0.53      1203

Weighted F1: 0.5288413323766856
Macro F1: 0.5300793930658984

Confusion Matrix:
 [[185 115  40]
 [148 249  92]
 [ 52 121 201]]
['Positive']

Classification Report:

                        precision    recall  f1-score   support

Constructive Criticism       0.57      0.86      0.68       614
         Cyberbullying       0.25      0.01      0.02       128
           Hate Speech       0.00      0.00      0.00        11
         Irony/Sarcasm       0.25      0.30      0.27        97
        Misinformation       0.00      0.00      0.00        14
             Offensive       0.60      0.05      0.09        61
                Others       0.58      0.29      0.39       278

              accuracy                           0.54      1203
             macro avg       0.32      0.22      0.21      1203
          weighted avg       0.50      0.54      0.47      1203

Weighted F1: 0.4671960844593571
Macro F1: 0.20754004025374112

Confusion Matrix:
 [[531   1   0  40   0   0  42]
 [105   1   0  18   0   1   3]
 [ 10   0   0   1   0   0   0]
 [ 60   0   0  29   0   0   8]
 [ 11   0   0   3   0   0   0]
 [ 50   0   0   2   0   3   6]
 [171   2   0  21   2   1  81]]

c:\Users\Lenovo\anaconda3\envs\learn-env\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

['Constructive Criticism']

Classification Report:

ValueError: Number of classes, 28, does not match size of target_names, 31. Try specifying the labels parameter