
#  SOCIAL MEDIA CYBERBULLYING DETECTION

Presented by:
1. Stella Kiarie

2. Kumati Dapash

3. Morvine Otieno

4. Doris Mutie

# 1. BUSINESS UNDERSTANDING

## 1.1 Overview   
The kenyan digital landscape is one of the most vibrant in Africa, driven by a huge population of young, tech savvy and a high rate of mobile internet usage.  The major platforms for social engagement, entertainment and business being FaceBook, YouTube, TikTok and X(formerly Twitter).  Content creators, artists, vloggers and commentators commanding millions of comments daily.   
Due to the anonymity and viral nature of these social media platforms, there is a developing culture if cyberbullying and online hostility. Unlike other Western countexts where comments fall under well known languages, Kenyan  comment section is characterized by code -switching between Kiswahili, English and Sheng. Sheng is mostly being used to deliver insults or to "roast" individuals in the online space.   

The current global cyberbulling moderation tools are primarily built in well-known languages like English, French, and a little bit of Swahili.  Following the Kenyan linguistic complexity, there moderation tools fail to capture harmful sheng Phrases which leave kenyan content creators, public figures and online users vulnerable to online harrassmenr which in turn results to severe mental issues, reputation damages, suicidal ideation and digital exclusion.    

Social media connects us, entertains us but sometimes it destroys us. Remember behind every trending post or hashtag, there is a real person with real feelings.

## 1.2  Problem Statement

There is a significant gap in the ability to automate systems that can detect and moderate cyberbulling within the linguistic Kenyan context.  
Comments from Kenyan social media posts are based on sheng or code switching context which often bypass the existing moderation tools. The linguistic nuances of toxic content remain online, fueling a hostile digital environment. Content creators and brands are unable to moderate thousands of multilingual comments in real time, resulting in a toxic feedback loop that damages engagement and mental well-being.

## 1.3 Challenges

1. Linguistic Fluidity: Sheng is not standardized and a word might differ in meaning in different locations.
2. Code-mixed content: mixing English, swahili and sheng in one comment often confuse the existing NLP models
3. High Volume: Kenyan social media and digital space generate thousands of comments within hours which limits human moderation.
4. Contexual Sarcasm: While sheng is being used, deep contexual understanding is required to classfy comments whether "bullying", "hatespeech" rather than "Humor/Irony/Sarcism "
5. Data Scarcity: There is no publicly available high quality datasets for sheng specifically labelled for toxicity

## 1.3  Proposed Solution

We propose building an adavanced multilingual NLP classification system specifically tuned for the Kenyan linguistic landscape. A structured annotation through label studio  for human annotation to ensure conssistent and high quality annotation of kenyan social media comments.  
Each commenyt presented to the annotator will be labelled through four sequential steps:
1. Language Identification
2. Sentiment Classification
3. Major Category Classification
4. subcategory Classification  
This hierachical labeling will help analyze bothe the general and detailed information about the social media text

1. Language Identification: identify the primary language used in the comment 
The major language options include:   
  
        1. English
        2. Swahili
        3. Sheng
        4. Mixed (Code-switching)
        5. Plain Emoji

2. Sentiment Annotation : After identifying the language, the annotators will label the sentiment expessed in the comment.  
The sentiment categories include: 

            1. Negative
            2. Positve
            3. Neutral   
Help understand the emotional tone of the message to detect harmful and constructive communications.

3. Major Category Classification : classify the comment into a main category that represents the overall nature of the message.   
The major categories include:

        1. Constructive Criticism
        2. Offensive Content
        3. Cyberbullying
        4. Hate Speech
        5. Irony/Sarcasm
        6. Misinformation
        7. Other

4. Subategory Classification: each major category is linked to specific subcategories. 
### Subcategories Used in Data Annotation

### Subcategories by Major Category

| Constructive Criticism | Offensive | Cyberbullying | Hate Speech | Irony/Sarcasm | Misinformation | Others |
|---|---|---|---|---|---|---|
| [CC] Performance-based | [Offensive] Sex-based | [Bullying] Body shaming | [Hate Speech] Gender based | [Irony] Mock compliment | [Misinfo] Fabricated Content (Fake News) | [Other] Spam |
| [CC] Corrective clarification | [Offensive] Vulgar language (Matusi) | [Bullying] Direct Insult | [Hate Speech] Political | [Irony] Mock Laughter | [Misinfo] Misleading/Contextual Deception | [Other] General Others |
| [CC] Decision-criticism | [Offensive] Non-personal | [Bullying] Threats | [Hate Speech] Ethical/racial group (Tribalism) | [Irony] Rhetorical Question | [Misinfo] Parody | [Other] General Inquiry |
| [CC] Genuine Praise |  | [Bullying] Humiliation | [Hate Speech] Disability | [Irony] Hyperbolic understatement |  |  |
| [CC] Supportive Speech |  | [Bullying] Exclusion tactics |  |  |  |  |
| [CC] Genuine feedback |  | [Bullying] Sexual harassment |  |  |  |  |
|  |  | [Bullying] Trolling |  |  |  |  |
|  |  | [Bullying] Defamation |  |  |  |  |

## 1.5 Objectives

The goal is to develop a robust ML model that identifies and flags cyberbullying in Sheng, Swahili, and English with high accuracy. 

•	Scrape and curate specialized datasets of more than 10,000 comments from Kenyan YouTube vlogs.  

•	Use human annotators (Fluent Sheng speakers) to create high-quality labelled datasets

•	Evaluating the model performance using F1-score, ensuring the model handles imbalanced data where bullying is less frequent than neutral comments. 

•	Build a prototype API or Dashboard that content creators can use to clean their comment sections automatically.

## 1.6 Success Criteria 
This project will be considered successful if:  

•	The model achieves an F1-Score of 75% or higher across the cyberbullying and hate speech categories. 

•	The system successfully identifies Sheng-specific insults that standard English filters miss.

# DATA UNDERSTANDING

## 2.1 Overview

To solve the problem identified in this project, we leveraged data from YoutubeTube comments from various Kenyan videos. The data will be scraped from YouTube using the YouTube Data API V3, an official and legal way of accessing public YouTube data for analysis. The project leverage the google-api-python-client interface with the comment Threads resource.   
The Scripts maps the raw JSON responses from YouTube and converts them into Pandas dataframe  
The data contains the following columns:  

•	Author: the public name of the commenter  
•	Text: raw comment content in plain text  
•	Likes: engagement metric  
•	Published at: Timestamp of the post.

Through this strategy, we managed to scrap  over 10,000 comments from Kenyan Youtube Content.

## 2.2 Labelling

### HUMAN DATA LABELLING AND ANNOTATION(Label Studio)

As compared to automated labeling methods, human annotators are better to interprate the nuances in the comments. 

Human annotation ensure accurate detection of harmful content in categories such as Cyberbullying, hate speech, offensive language and Sarcasm . These categories require human judgement because the meaning often depends on context and intention.   
* Human labeling helps ensure:  
* Correct classification of comments  
* Reliable sentiment detection  
* Consistent labeling across categories  
* High-quality training data for the NLP model.

## 2.3 Data Quality issues

Major data quality issues during the annotation process include;
1. A significant amount of data use non standard english hence annotator needs a local Kenyan Slang understanding to accurately identify the segments
2. class imbalance: Categories such as Contructive critism and Irony appear way more than other .
3. Certain names appear in toxic comments highlihting a need for annymization(masking). In data preparation to prevent the model from learninf "name_based" bias.

## Data Loading and Inspection

In [27]:
import sys
import os

sys.path.append(os.path.abspath(".."))
 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## Import Class Modules 
from Data_prep.loader import DataLoader
from Data_prep.eda import EDA

### Loading Dataset in a Dataframe

In [28]:
loader=DataLoader('Labelled_data.csv')
data= loader.load_data()
data.head()

✅ Dataset loaded successfully from Labelled_data.csv

,Unnamed: 0,Unnamed: 0.1,annotation_id,annotator,author,category,clean_text,confidence_score,created_at,id,language,lead_time,likes,predicted_label,published_at,sentiment,subcategory,text,updated_at
0,NaN,0,2906,1,@ChristineArumba-y7q,Irony/Sarcasm,rolling_on_the_floor_laughing rolling_on_the...,0.440840,2026-02-24T19:51:18.322618Z,84722,Plain Emoji,3461.997,0,offensive language,2026-02-15T10:58:38Z,Neutral,[Irony] Mock compliment,🤣🤣🤣🤣🤣🤣🤣🤣🤣,2026-02-24T19:51:18.322618Z
1,NaN,1,2907,1,@LexiSumaii,Irony/Sarcasm,OBina suffer alot face_with_tears_of_joy fac...,0.585292,2026-02-24T20:07:26.863676Z,84723,Mixed (Code-switching),968.237,0,offensive language,2026-02-09T21:24:41Z,Negative,[Irony] Mock Laughter,OBina suffer alot 😂😂😂😂,2026-02-24T20:07:26.863676Z
2,NaN,2,2908,1,@marthaayuma7065,Irony/Sarcasm,Mmmmh makubwa yapo njiani yanakuja,0.324890,2026-02-24T20:26:31.625564Z,84724,Swahili,1144.328,0,neutral or positive,2026-02-08T02:19:02Z,Neutral,[Irony] Mock compliment,Mmmmh makubwa yapo njiani yanakuja,2026-02-24T20:26:31.625564Z
3,NaN,3,2909,1,@danwenger1113,Offensive,Tunataka \r\nKiss between \r\n\r\nSalet and On...,0.335128,2026-02-24T20:26:48.639404Z,84725,Mixed (Code-switching),16.544,0,constructive criticism,2026-02-07T14:27:42Z,Negative,[Offensive] Sex-based,Tunataka \r\nKiss between \r\n\r\nSalet and On...,2026-02-24T20:26:48.639404Z
4,NaN,4,2910,1,@emmambuvi9029,Offensive,Foolishness and witchcraft,0.592672,2026-02-24T20:27:23.278088Z,84726,English,34.206,0,offensive language,2026-02-07T07:41:52Z,Negative,[Offensive] Non-personal,Foolishness and witchcraft,2026-02-24T20:27:23.278088Z

### Dropping Colums

In [29]:
columns_to_drop= ["Unnamed: 0","Unnamed: 0.1","annotation_id","annotator",
                  "author","clean_text","confidence_score","created_at","id",
                  "lead_time","predicted_label","updated_at"]
data=loader.drop_irrelevant_columns(columns_to_drop)

✅ Dropped columns: ['Unnamed: 0', 'Unnamed: 0.1', 'annotation_id', 'annotator', 'author', 'clean_text', 'confidence_score', 'created_at', 'id', 'lead_time', 'predicted_label', 'updated_at']
New shape: (3856, 7)

In [30]:
data.columns

Index(['category', 'language', 'likes', 'published_at', 'sentiment',
       'subcategory', 'text'],
      dtype='object')

### Checking Info

In [31]:
loader.check_info()

📊 DATA INFO
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3856 entries, 0 to 3855
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   category      3856 non-null   object
 1   language      3856 non-null   object
 2   likes         3856 non-null   int64
 3   published_at  3856 non-null   object
 4   sentiment     3856 non-null   object
 5   subcategory   3847 non-null   object
 6   text          3855 non-null   object
dtypes: int64(1), object(6)
memory usage: 211.0+ KB
None

Shape: (3856, 7)

## Checking for missing Values

In [32]:
loader.check_missing_values()

🔎 MISSING VALUES
==================================================
category        0
language        0
likes           0
published_at    0
sentiment       0
subcategory     9
text            1
dtype: int64

category        0
language        0
likes           0
published_at    0
sentiment       0
subcategory     9
text            1
dtype: int64

### Drop missing values

In [33]:
loader.drop_missing_values()

✅ Dropped 10 rows with missing values.
New shape: (3846, 7)

,category,language,likes,published_at,sentiment,subcategory,text
0,Irony/Sarcasm,Plain Emoji,0,2026-02-15T10:58:38Z,Neutral,[Irony] Mock compliment,🤣🤣🤣🤣🤣🤣🤣🤣🤣
1,Irony/Sarcasm,Mixed (Code-switching),0,2026-02-09T21:24:41Z,Negative,[Irony] Mock Laughter,OBina suffer alot 😂😂😂😂
2,Irony/Sarcasm,Swahili,0,2026-02-08T02:19:02Z,Neutral,[Irony] Mock compliment,Mmmmh makubwa yapo njiani yanakuja
3,Offensive,Mixed (Code-switching),0,2026-02-07T14:27:42Z,Negative,[Offensive] Sex-based,Tunataka \r\nKiss between \r\n\r\nSalet and On...
4,Offensive,English,0,2026-02-07T07:41:52Z,Negative,[Offensive] Non-personal,Foolishness and witchcraft
...,...,...,...,...,...,...,...
3851,Constructive Criticism,Sheng,1,2026-01-31T04:53:21Z,Neutral,[CC] Performance-based,Hii inadai khaligraph Pon de beat remixed #nug...
3852,Others,Mixed (Code-switching),0,2026-01-31T04:53:08Z,Neutral,[Other] General Others,Kinena kuna vitu haikosi 🔪🔫
3853,Others,Mixed (Code-switching),0,2026-01-31T04:51:37Z,Neutral,[Other] General Others,Sawa Arees
3854,Constructive Criticism,English,1,2026-01-31T04:48:30Z,Positive,[CC] Genuine Praise,Who here before millions 🎉🎉🎉
3855,Constructive Criticism,Mixed (Code-switching),0,2026-01-31T04:47:39Z,Positive,[CC] Genuine Praise,From kisii mimi napenda uyu chamaa walai 😂😂😂 h...

In [34]:
loader.check_shape()

📐 Current Shape: (3846, 7)

(3846, 7)

### Check for Duplicates

In [35]:
loader.check_duplicates()

🔁 Duplicate rows: 1

np.int64(1)

In [36]:
loader.drop_duplicates()

✅ Removed 1 duplicate rows.
New shape: (3845, 7)

,category,language,likes,published_at,sentiment,subcategory,text
0,Irony/Sarcasm,Plain Emoji,0,2026-02-15T10:58:38Z,Neutral,[Irony] Mock compliment,🤣🤣🤣🤣🤣🤣🤣🤣🤣
1,Irony/Sarcasm,Mixed (Code-switching),0,2026-02-09T21:24:41Z,Negative,[Irony] Mock Laughter,OBina suffer alot 😂😂😂😂
2,Irony/Sarcasm,Swahili,0,2026-02-08T02:19:02Z,Neutral,[Irony] Mock compliment,Mmmmh makubwa yapo njiani yanakuja
3,Offensive,Mixed (Code-switching),0,2026-02-07T14:27:42Z,Negative,[Offensive] Sex-based,Tunataka \r\nKiss between \r\n\r\nSalet and On...
4,Offensive,English,0,2026-02-07T07:41:52Z,Negative,[Offensive] Non-personal,Foolishness and witchcraft
...,...,...,...,...,...,...,...
3851,Constructive Criticism,Sheng,1,2026-01-31T04:53:21Z,Neutral,[CC] Performance-based,Hii inadai khaligraph Pon de beat remixed #nug...
3852,Others,Mixed (Code-switching),0,2026-01-31T04:53:08Z,Neutral,[Other] General Others,Kinena kuna vitu haikosi 🔪🔫
3853,Others,Mixed (Code-switching),0,2026-01-31T04:51:37Z,Neutral,[Other] General Others,Sawa Arees
3854,Constructive Criticism,English,1,2026-01-31T04:48:30Z,Positive,[CC] Genuine Praise,Who here before millions 🎉🎉🎉
3855,Constructive Criticism,Mixed (Code-switching),0,2026-01-31T04:47:39Z,Positive,[CC] Genuine Praise,From kisii mimi napenda uyu chamaa walai 😂😂😂 h...

### Standardizing columnns and Column Names

In [37]:
loader.standardize_column_names()

✅ Column names standardized.
New columns: ['category', 'language', 'likes', 'published_at', 'sentiment', 'subcategory', 'text']

,category,language,likes,published_at,sentiment,subcategory,text
0,Irony/Sarcasm,Plain Emoji,0,2026-02-15T10:58:38Z,Neutral,[Irony] Mock compliment,🤣🤣🤣🤣🤣🤣🤣🤣🤣
1,Irony/Sarcasm,Mixed (Code-switching),0,2026-02-09T21:24:41Z,Negative,[Irony] Mock Laughter,OBina suffer alot 😂😂😂😂
2,Irony/Sarcasm,Swahili,0,2026-02-08T02:19:02Z,Neutral,[Irony] Mock compliment,Mmmmh makubwa yapo njiani yanakuja
3,Offensive,Mixed (Code-switching),0,2026-02-07T14:27:42Z,Negative,[Offensive] Sex-based,Tunataka \r\nKiss between \r\n\r\nSalet and On...
4,Offensive,English,0,2026-02-07T07:41:52Z,Negative,[Offensive] Non-personal,Foolishness and witchcraft
...,...,...,...,...,...,...,...
3851,Constructive Criticism,Sheng,1,2026-01-31T04:53:21Z,Neutral,[CC] Performance-based,Hii inadai khaligraph Pon de beat remixed #nug...
3852,Others,Mixed (Code-switching),0,2026-01-31T04:53:08Z,Neutral,[Other] General Others,Kinena kuna vitu haikosi 🔪🔫
3853,Others,Mixed (Code-switching),0,2026-01-31T04:51:37Z,Neutral,[Other] General Others,Sawa Arees
3854,Constructive Criticism,English,1,2026-01-31T04:48:30Z,Positive,[CC] Genuine Praise,Who here before millions 🎉🎉🎉
3855,Constructive Criticism,Mixed (Code-switching),0,2026-01-31T04:47:39Z,Positive,[CC] Genuine Praise,From kisii mimi napenda uyu chamaa walai 😂😂😂 h...

In [38]:
loader.clean_subcategory()

✅ Cleaned 'subcategory' column.

,category,language,likes,published_at,sentiment,subcategory,text
0,Irony/Sarcasm,Plain Emoji,0,2026-02-15T10:58:38Z,Neutral,Mock compliment,🤣🤣🤣🤣🤣🤣🤣🤣🤣
1,Irony/Sarcasm,Mixed (Code-switching),0,2026-02-09T21:24:41Z,Negative,Mock Laughter,OBina suffer alot 😂😂😂😂
2,Irony/Sarcasm,Swahili,0,2026-02-08T02:19:02Z,Neutral,Mock compliment,Mmmmh makubwa yapo njiani yanakuja
3,Offensive,Mixed (Code-switching),0,2026-02-07T14:27:42Z,Negative,Sex-based,Tunataka \r\nKiss between \r\n\r\nSalet and On...
4,Offensive,English,0,2026-02-07T07:41:52Z,Negative,Non-personal,Foolishness and witchcraft
...,...,...,...,...,...,...,...
3851,Constructive Criticism,Sheng,1,2026-01-31T04:53:21Z,Neutral,Performance-based,Hii inadai khaligraph Pon de beat remixed #nug...
3852,Others,Mixed (Code-switching),0,2026-01-31T04:53:08Z,Neutral,General Others,Kinena kuna vitu haikosi 🔪🔫
3853,Others,Mixed (Code-switching),0,2026-01-31T04:51:37Z,Neutral,General Others,Sawa Arees
3854,Constructive Criticism,English,1,2026-01-31T04:48:30Z,Positive,Genuine Praise,Who here before millions 🎉🎉🎉
3855,Constructive Criticism,Mixed (Code-switching),0,2026-01-31T04:47:39Z,Positive,Genuine Praise,From kisii mimi napenda uyu chamaa walai 😂😂😂 h...

In [39]:
loader.clean_language_column()

✅ Cleaned 'language' column.

,category,language,likes,published_at,sentiment,subcategory,text
0,Irony/Sarcasm,Plain Emoji,0,2026-02-15T10:58:38Z,Neutral,Mock compliment,🤣🤣🤣🤣🤣🤣🤣🤣🤣
1,Irony/Sarcasm,Code Switching,0,2026-02-09T21:24:41Z,Negative,Mock Laughter,OBina suffer alot 😂😂😂😂
2,Irony/Sarcasm,Swahili,0,2026-02-08T02:19:02Z,Neutral,Mock compliment,Mmmmh makubwa yapo njiani yanakuja
3,Offensive,Code Switching,0,2026-02-07T14:27:42Z,Negative,Sex-based,Tunataka \r\nKiss between \r\n\r\nSalet and On...
4,Offensive,English,0,2026-02-07T07:41:52Z,Negative,Non-personal,Foolishness and witchcraft
...,...,...,...,...,...,...,...
3851,Constructive Criticism,Sheng,1,2026-01-31T04:53:21Z,Neutral,Performance-based,Hii inadai khaligraph Pon de beat remixed #nug...
3852,Others,Code Switching,0,2026-01-31T04:53:08Z,Neutral,General Others,Kinena kuna vitu haikosi 🔪🔫
3853,Others,Code Switching,0,2026-01-31T04:51:37Z,Neutral,General Others,Sawa Arees
3854,Constructive Criticism,English,1,2026-01-31T04:48:30Z,Positive,Genuine Praise,Who here before millions 🎉🎉🎉
3855,Constructive Criticism,Code Switching,0,2026-01-31T04:47:39Z,Positive,Genuine Praise,From kisii mimi napenda uyu chamaa walai 😂😂😂 h...

# 📊 Exploratory Data Analysis (EDA)

## Introduction

This section explores the structure, distribution, and characteristics of the cyberbullying dataset before modeling.  
The goal is to understand patterns in categories, sentiment, text behavior, language usage, and posting activity.

In [40]:
eda = EDA(loader.data)

### A) Dataset Overview

The dataset overview examined the structure and quality of the data.  
This included checking the number of rows and columns, data types, column names, and missing values.  

This step ensured the dataset is clean, properly formatted, and ready for deeper exploratory analysis and modeling.

In [41]:

eda.dataset_overview()

📊 DATASET OVERVIEW
============================================================
Shape: (3845, 7)

Columns:
['category', 'language', 'likes', 'published_at', 'sentiment', 'subcategory', 'text']

Data Types:
category        object
language        object
likes            int64
published_at    object
sentiment       object
subcategory     object
text            object
dtype: object

Missing Values:
category        0
language        0
likes           0
published_at    0
sentiment       0
subcategory     0
text            0
dtype: int64

### B) Target Distribution Analysis

This analysis explored the distribution of posts across different cyberbullying categories and sentiment classes.  

Understanding class balance is important for machine learning, as imbalanced data may require resampling or class weighting.  
The sentiment distribution also provides insight into the overall emotional tone of the dataset.

In [42]:
eda.target_distribution("category")

Class Percentages:
category
Constructive Criticism    51.60
Others                    24.84
Irony/Sarcasm              9.34
Cyberbullying              7.23
Offensive                  5.23
Misinformation             1.20
Hate Speech                0.57
Name: proportion, dtype: float64

In [43]:
eda.target_distribution("sentiment")

Class Percentages:
sentiment
Neutral     41.82
Positive    31.81
Negative    26.37
Name: proportion, dtype: float64

### C) Subcategory Analysis

The subcategory analysis examined more detailed classifications of cyberbullying behavior.  

This helps identify dominant bullying patterns and determines whether fine-grained classification is feasible.  
It also highlights subcategories that may require balancing during model training.

In [44]:
eda.subcategory_analysis()

### D) Text Length Analysis

Text length analysis evaluated the distribution of post lengths in characters.  

This insight helps determine appropriate tokenization limits, sequence lengths for NLP models, and detection of unusually short or long posts that may affect model performance.

In [45]:
eda.text_length_analysis()

Text Length Summary:
count    3845.000000
mean       49.200780
std        52.014033
min         1.000000
25%        20.000000
50%        35.000000
75%        61.000000
max      1020.000000
Name: text_length, dtype: float64

### E) Language Distribution

The language distribution analysis identified the dominant languages used in the dataset.  

This is important for preprocessing decisions such as stopword removal, tokenization strategy, and determining whether multilingual modeling is required.

In [46]:
eda.language_insights()

Language Percentages:
language
Code Switching    45.44
English           19.66
Sheng             18.21
Swahili           13.97
Plain Emoji        2.73
Name: proportion, dtype: float64

### F) Peak Posting Time Analysis (Kenyan Time - EAT)

This analysis converted timestamps to Kenyan time (EAT - UTC+3) and examined hourly posting patterns.  

Identifying peak activity hours provides behavioral insights into when cyberbullying is most active and may support real-time moderation strategies.  
Weekend and weekday comparisons further contextualize user behavior.

In [47]:
eda.peak_posting_times("published_at")

🕒 Posting Activity by Hour
============================================================
hour
0     371
1     129
2      63
3      42
4      42
5      32
6      38
7      74
8     150
9     167
10    178
11    170
12    187
13    202
14    163
15    164
16    179
17    157
18    179
19    241
20    134
21    178
22    202
23    403
Name: count, dtype: int64

🔥 Peak Posting Hour:
23:00

📅 Weekend vs Weekday Activity
============================================================
is_weekend
False    2494
True     1351
Name: hour, dtype: int64

hour
0     371
1     129
2      63
3      42
4      42
5      32
6      38
7      74
8     150
9     167
10    178
11    170
12    187
13    202
14    163
15    164
16    179
17    157
18    179
19    241
20    134
21    178
22    202
23    403
Name: count, dtype: int64

### G) Key Findings Summary

The key findings section summarized major insights from the EDA process, including dominant categories, sentiment trends, language patterns, and average text length.  

These insights guide preprocessing decisions, feature engineering, and model development strategies for the cyberbullying detection system.

In [48]:
eda.key_findings()

🔎 KEY FINDINGS SUMMARY
============================================================
Total Samples: 3845

Top Category:
Constructive Criticism

Top Sentiment:
Neutral

Most Common Language:
Code Switching

Average Text Length: 49.20 characters

## Data Pre - proccessing

In [49]:
from Data_prep.preprocesssing import TextPreprocessor

preprocessor = TextPreprocessor()

In [ ]:
df = preprocessor.transform(data, column="text")
df.head()