
#  SOCIAL MEDIA CYBERBULLYING DETECTION

Presented by:
1. Stella Kiarie

2. Kumati Dapash

3. Morvine Otieno

4. Doris Mutie

# 1. BUSINESS UNDERSTANDING

## 1.1 Overview   
The kenyan digital landscape is one of the most vibrant in Africa, driven by a huge population of young, tech savvy and a high rate of mobile internet usage.  The major platforms for social engagement, entertainment and business being FaceBook, YouTube, TikTok and X(formerly Twitter).  Content creators, artists, vloggers and commentators commanding millions of comments daily.   
Due to the anonymity and viral nature of these social media platforms, there is a developing culture if cyberbullying and online hostility. Unlike other Western countexts where comments fall under well known languages, Kenyan  comment section is characterized by code -switching between Kiswahili, English and Sheng. Sheng is mostly being used to deliver insults or to "roast" individuals in the online space.   

The current global cyberbulling moderation tools are primarily built in well-known languages like English, French, and a little bit of Swahili.  Following the Kenyan linguistic complexity, there moderation tools fail to capture harmful sheng Phrases which leave kenyan content creators, public figures and online users vulnerable to online harrassmenr which in turn results to severe mental issues, reputation damages, suicidal ideation and digital exclusion.    

Social media connects us, entertains us but sometimes it destroys us. Remember behind every trending post or hashtag, there is a real person with real feelings.

## 1.2  Problem Statement

There is a significant gap in the ability to automate systems that can detect and moderate cyberbulling within the linguistic Kenyan context.  
Comments from Kenyan social media posts are based on sheng or code switching context which often bypass the existing moderation tools. The linguistic nuances of toxic content remain online, fueling a hostile digital environment. Content creators and brands are unable to moderate thousands of multilingual comments in real time, resulting in a toxic feedback loop that damages engagement and mental well-being.

## 1.3 Challenges

1. Linguistic Fluidity: Sheng is not standardized and a word might differ in meaning in different locations.
2. Code-mixed content: mixing English, swahili and sheng in one comment often confuse the existing NLP models
3. High Volume: Kenyan social media and digital space generate thousands of comments within hours which limits human moderation.
4. Contexual Sarcasm: While sheng is being used, deep contexual understanding is required to classfy comments whether "bullying", "hatespeech" rather than "Humor/Irony/Sarcism "
5. Data Scarcity: There is no publicly available high quality datasets for sheng specifically labelled for toxicity

## 1.3  Proposed Solution

We propose building an adavanced multilingual NLP classification system specifically tuned for the Kenyan linguistic landscape. A structured annotation through label studio  for human annotation to ensure conssistent and high quality annotation of kenyan social media comments.  
Each commenyt presented to the annotator will be labelled through four sequential steps:
1. Language Identification
2. Sentiment Classification
3. Major Category Classification
4. subcategory Classification  
This hierachical labeling will help analyze bothe the general and detailed information about the social media text

1. Language Identification: identify the primary language used in the comment 
The major language options include:   
  
        1. English
        2. Swahili
        3. Sheng
        4. Mixed (Code-switching)
        5. Plain Emoji

2. Sentiment Annotation : After identifying the language, the annotators will label the sentiment expessed in the comment.  
The sentiment categories include: 

            1. Negative
            2. Positve
            3. Neutral   
Help understand the emotional tone of the message to detect harmful and constructive communications.

3. Major Category Classification : classify the comment into a main category that represents the overall nature of the message.   
The major categories include:

        1. Constructive Criticism
        2. Offensive Content
        3. Cyberbullying
        4. Hate Speech
        5. Irony/Sarcasm
        6. Misinformation
        7. Other

4. Subategory Classification: each major category is linked to specific subcategories. 
### Subcategories Used in Data Annotation

### Subcategories by Major Category

| Constructive Criticism | Offensive | Cyberbullying | Hate Speech | Irony/Sarcasm | Misinformation | Others |
|---|---|---|---|---|---|---|
| [CC] Performance-based | [Offensive] Sex-based | [Bullying] Body shaming | [Hate Speech] Gender based | [Irony] Mock compliment | [Misinfo] Fabricated Content (Fake News) | [Other] Spam |
| [CC] Corrective clarification | [Offensive] Vulgar language (Matusi) | [Bullying] Direct Insult | [Hate Speech] Political | [Irony] Mock Laughter | [Misinfo] Misleading/Contextual Deception | [Other] General Others |
| [CC] Decision-criticism | [Offensive] Non-personal | [Bullying] Threats | [Hate Speech] Ethical/racial group (Tribalism) | [Irony] Rhetorical Question | [Misinfo] Parody | [Other] General Inquiry |
| [CC] Genuine Praise |  | [Bullying] Humiliation | [Hate Speech] Disability | [Irony] Hyperbolic understatement |  |  |
| [CC] Supportive Speech |  | [Bullying] Exclusion tactics |  |  |  |  |
| [CC] Genuine feedback |  | [Bullying] Sexual harassment |  |  |  |  |
|  |  | [Bullying] Trolling |  |  |  |  |
|  |  | [Bullying] Defamation |  |  |  |  |

## 1.5 Objectives

The goal is to develop a robust ML model that identifies and flags cyberbullying in Sheng, Swahili, and English with high accuracy. 

•	Scrape and curate specialized datasets of more than 10,000 comments from Kenyan YouTube vlogs.  

•	Use human annotators (Fluent Sheng speakers) to create high-quality labelled datasets

•	Evaluating the model performance using F1-score, ensuring the model handles imbalanced data where bullying is less frequent than neutral comments. 

•	Build a prototype API or Dashboard that content creators can use to clean their comment sections automatically.

## 1.6 Success Criteria 
This project will be considered successful if:  

•	The model achieves an F1-Score of 75% or higher across the cyberbullying and hate speech categories. 

•	The system successfully identifies Sheng-specific insults that standard English filters miss.

# DATA UNDERSTANDING

## 2.1 Overview

To solve the problem identified in this project, we leveraged data from YoutubeTube comments from various Kenyan videos. The data will be scraped from YouTube using the YouTube Data API V3, an official and legal way of accessing public YouTube data for analysis. The project leverage the google-api-python-client interface with the comment Threads resource.   
The Scripts maps the raw JSON responses from YouTube and converts them into Pandas dataframe  
The data contains the following columns:  

•	Author: the public name of the commenter  
•	Text: raw comment content in plain text  
•	Likes: engagement metric  
•	Published at: Timestamp of the post.

Through this strategy, we managed to scrap  over 10,000 comments from Kenyan Youtube Content.

## 2.2 Labelling

### HUMAN DATA LABELLING AND ANNOTATION(Label Studio)

As compared to automated labeling methods, human annotators are better to interprate the nuances in the comments. 

Human annotation ensure accurate detection of harmful content in categories such as Cyberbullying, hate speech, offensive language and Sarcasm . These categories require human judgement because the meaning often depends on context and intention.   
* Human labeling helps ensure:  
* Correct classification of comments  
* Reliable sentiment detection  
* Consistent labeling across categories  
* High-quality training data for the NLP model.

## 2.3 Data Quality issues

Major data quality issues during the annotation process include;
1. A significant amount of data use non standard english hence annotator needs a local Kenyan Slang understanding to accurately identify the segments
2. class imbalance: Categories such as Contructive critism and Irony appear way more than other .
3. Certain names appear in toxic comments highlihting a need for annymization(masking). In data preparation to prevent the model from learninf "name_based" bias.

## Data Loading and Inspection

In [37]:
import sys
import os

sys.path.append(os.path.abspath(".."))
 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## Import Class Modules 
from Data_prep.loader import DataLoader
from Data_prep.eda import EDA

### Loading Dataset in a Dataframe

In [38]:
loader=DataLoader('final_data.csv')
data= loader.load_data()
data.head()

✅ Dataset loaded successfully from final_data.csv

,Unnamed: 0.2,Unnamed: 0,Unnamed: 0.1,annotation_id,annotator,author,category,clean_text,confidence_score,created_at,id,language,lead_time,likes,predicted_label,published_at,sentiment,subcategory,text,updated_at
0,0,NaN,5028,3011,1,@Annemimi234,Irony/Sarcasm,Napenda hii couple but hapo kwa 29yrs nimekata...,0.604895,2026-02-24T19:06:10.770015Z,10057,Mixed (Code-switching),224.696,10,neutral or positive,2025-07-28T16:36:04Z,Positive,[Irony] Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...,2026-02-24T19:06:10.770015Z
1,1,NaN,5029,3012,1,@MKLMNMKLMNMKLMN,Others,rada zako wasingam,0.291550,2026-02-24T19:08:59.913717Z,10058,Sheng,90.467,0,neutral or positive,2025-07-28T16:35:44Z,Neutral,[Other] General Others,rada zako wasingam,2026-02-24T19:08:59.913717Z
2,2,NaN,5030,3013,1,@raphaelmutinda8214,Constructive Criticism,Izo chwom mbaya ndio zetuu face_with_tears_of_...,0.623743,2026-02-24T19:10:09.116244Z,10059,Sheng,67.516,0,offensive language,2025-07-28T16:35:12Z,Positive,[CC] Genuine Praise,Izo chwom mbaya ndio zetuu😂😂,2026-02-24T19:10:09.116244Z
3,3,NaN,5031,3014,1,@rhinoriders6060,Constructive Criticism,Nka shy grinning_face_with_sweat,0.407087,2026-02-24T19:11:05.157793Z,10060,Mixed (Code-switching),53.456,0,neutral or positive,2025-07-28T16:35:07Z,Positive,[CC] Genuine Praise,Nka shy😅,2026-02-24T19:11:05.157793Z
4,4,NaN,5032,3015,1,@wanjawakariuki9079,Constructive Criticism,Ata kama ni dooh kuna shida zingine siwezi taka,0.627657,2026-02-24T19:18:26.750854Z,10061,Sheng,70.046,1,neutral or positive,2025-07-28T16:34:43Z,Neutral,[CC] Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka,2026-02-24T19:18:26.750854Z

### Dropping Colums

In [39]:
columns_to_drop= ["Unnamed: 0","Unnamed: 0.2","Unnamed: 0.1","annotation_id","annotator",
                  "author","clean_text","confidence_score","created_at","id",
                  "lead_time","predicted_label","updated_at"]
data=loader.drop_irrelevant_columns(columns_to_drop)

✅ Dropped columns: ['Unnamed: 0', 'Unnamed: 0.2', 'Unnamed: 0.1', 'annotation_id', 'annotator', 'author', 'clean_text', 'confidence_score', 'created_at', 'id', 'lead_time', 'predicted_label', 'updated_at']
New shape: (6031, 7)

In [40]:
data.columns

Index(['category', 'language', 'likes', 'published_at', 'sentiment',
       'subcategory', 'text'],
      dtype='object')

### Checking Info

In [41]:
loader.check_info()

📊 DATA INFO
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6031 entries, 0 to 6030
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   category      6031 non-null   object
 1   language      6031 non-null   object
 2   likes         6031 non-null   int64
 3   published_at  6031 non-null   object
 4   sentiment     6031 non-null   object
 5   subcategory   6013 non-null   object
 6   text          6030 non-null   object
dtypes: int64(1), object(6)
memory usage: 329.9+ KB
None

Shape: (6031, 7)

## Checking for missing Values

In [42]:
loader.check_missing_values()

🔎 MISSING VALUES
==================================================
category         0
language         0
likes            0
published_at     0
sentiment        0
subcategory     18
text             1
dtype: int64

category         0
language         0
likes            0
published_at     0
sentiment        0
subcategory     18
text             1
dtype: int64

### Drop missing values

In [43]:
loader.drop_missing_values()

✅ Dropped 19 rows with missing values.
New shape: (6012, 7)

,category,language,likes,published_at,sentiment,subcategory,text
0,Irony/Sarcasm,Mixed (Code-switching),10,2025-07-28T16:36:04Z,Positive,[Irony] Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...
1,Others,Sheng,0,2025-07-28T16:35:44Z,Neutral,[Other] General Others,rada zako wasingam
2,Constructive Criticism,Sheng,0,2025-07-28T16:35:12Z,Positive,[CC] Genuine Praise,Izo chwom mbaya ndio zetuu😂😂
3,Constructive Criticism,Mixed (Code-switching),0,2025-07-28T16:35:07Z,Positive,[CC] Genuine Praise,Nka shy😅
4,Constructive Criticism,Sheng,1,2025-07-28T16:34:43Z,Neutral,[CC] Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka
...,...,...,...,...,...,...,...
6026,Irony/Sarcasm,Sheng,0,2025-07-28T16:38:05Z,Negative,[Irony] Mock compliment,Wenye hawajui venye street hu-run mnafloat tu😂...
6027,Constructive Criticism,English,0,2025-07-28T16:37:50Z,Positive,[CC] Genuine feedback,I can answer that question more further😂😂😂😂😂😂
6028,Constructive Criticism,English,2,2025-07-28T16:37:39Z,Positive,[CC] Genuine Praise,wedding of the year ❤❤
6029,Constructive Criticism,Sheng,1,2025-07-28T16:37:19Z,Neutral,[CC] Supportive Speech,"Hiyo wedding nayo , episode 2000 and I can’t g..."
6030,Constructive Criticism,English,7,2025-07-28T16:36:14Z,Positive,[CC] Genuine feedback,"I like the suit Obinna is wearing. Well, the c..."

In [44]:
loader.check_shape()

📐 Current Shape: (6012, 7)

(6012, 7)

### Check for Duplicates

In [45]:
loader.check_duplicates()

🔁 Duplicate rows: 1

np.int64(1)

In [46]:
loader.drop_duplicates()

✅ Removed 1 duplicate rows.
New shape: (6011, 7)

,category,language,likes,published_at,sentiment,subcategory,text
0,Irony/Sarcasm,Mixed (Code-switching),10,2025-07-28T16:36:04Z,Positive,[Irony] Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...
1,Others,Sheng,0,2025-07-28T16:35:44Z,Neutral,[Other] General Others,rada zako wasingam
2,Constructive Criticism,Sheng,0,2025-07-28T16:35:12Z,Positive,[CC] Genuine Praise,Izo chwom mbaya ndio zetuu😂😂
3,Constructive Criticism,Mixed (Code-switching),0,2025-07-28T16:35:07Z,Positive,[CC] Genuine Praise,Nka shy😅
4,Constructive Criticism,Sheng,1,2025-07-28T16:34:43Z,Neutral,[CC] Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka
...,...,...,...,...,...,...,...
6026,Irony/Sarcasm,Sheng,0,2025-07-28T16:38:05Z,Negative,[Irony] Mock compliment,Wenye hawajui venye street hu-run mnafloat tu😂...
6027,Constructive Criticism,English,0,2025-07-28T16:37:50Z,Positive,[CC] Genuine feedback,I can answer that question more further😂😂😂😂😂😂
6028,Constructive Criticism,English,2,2025-07-28T16:37:39Z,Positive,[CC] Genuine Praise,wedding of the year ❤❤
6029,Constructive Criticism,Sheng,1,2025-07-28T16:37:19Z,Neutral,[CC] Supportive Speech,"Hiyo wedding nayo , episode 2000 and I can’t g..."
6030,Constructive Criticism,English,7,2025-07-28T16:36:14Z,Positive,[CC] Genuine feedback,"I like the suit Obinna is wearing. Well, the c..."

### Standardizing columnns and Column Names

In [47]:
loader.standardize_column_names()

✅ Column names standardized.
New columns: ['category', 'language', 'likes', 'published_at', 'sentiment', 'subcategory', 'text']

,category,language,likes,published_at,sentiment,subcategory,text
0,Irony/Sarcasm,Mixed (Code-switching),10,2025-07-28T16:36:04Z,Positive,[Irony] Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...
1,Others,Sheng,0,2025-07-28T16:35:44Z,Neutral,[Other] General Others,rada zako wasingam
2,Constructive Criticism,Sheng,0,2025-07-28T16:35:12Z,Positive,[CC] Genuine Praise,Izo chwom mbaya ndio zetuu😂😂
3,Constructive Criticism,Mixed (Code-switching),0,2025-07-28T16:35:07Z,Positive,[CC] Genuine Praise,Nka shy😅
4,Constructive Criticism,Sheng,1,2025-07-28T16:34:43Z,Neutral,[CC] Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka
...,...,...,...,...,...,...,...
6026,Irony/Sarcasm,Sheng,0,2025-07-28T16:38:05Z,Negative,[Irony] Mock compliment,Wenye hawajui venye street hu-run mnafloat tu😂...
6027,Constructive Criticism,English,0,2025-07-28T16:37:50Z,Positive,[CC] Genuine feedback,I can answer that question more further😂😂😂😂😂😂
6028,Constructive Criticism,English,2,2025-07-28T16:37:39Z,Positive,[CC] Genuine Praise,wedding of the year ❤❤
6029,Constructive Criticism,Sheng,1,2025-07-28T16:37:19Z,Neutral,[CC] Supportive Speech,"Hiyo wedding nayo , episode 2000 and I can’t g..."
6030,Constructive Criticism,English,7,2025-07-28T16:36:14Z,Positive,[CC] Genuine feedback,"I like the suit Obinna is wearing. Well, the c..."

In [48]:
loader.clean_subcategory()

✅ Cleaned 'subcategory' column.

,category,language,likes,published_at,sentiment,subcategory,text
0,Irony/Sarcasm,Mixed (Code-switching),10,2025-07-28T16:36:04Z,Positive,Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...
1,Others,Sheng,0,2025-07-28T16:35:44Z,Neutral,General Others,rada zako wasingam
2,Constructive Criticism,Sheng,0,2025-07-28T16:35:12Z,Positive,Genuine Praise,Izo chwom mbaya ndio zetuu😂😂
3,Constructive Criticism,Mixed (Code-switching),0,2025-07-28T16:35:07Z,Positive,Genuine Praise,Nka shy😅
4,Constructive Criticism,Sheng,1,2025-07-28T16:34:43Z,Neutral,Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka
...,...,...,...,...,...,...,...
6026,Irony/Sarcasm,Sheng,0,2025-07-28T16:38:05Z,Negative,Mock compliment,Wenye hawajui venye street hu-run mnafloat tu😂...
6027,Constructive Criticism,English,0,2025-07-28T16:37:50Z,Positive,Genuine feedback,I can answer that question more further😂😂😂😂😂😂
6028,Constructive Criticism,English,2,2025-07-28T16:37:39Z,Positive,Genuine Praise,wedding of the year ❤❤
6029,Constructive Criticism,Sheng,1,2025-07-28T16:37:19Z,Neutral,Supportive Speech,"Hiyo wedding nayo , episode 2000 and I can’t g..."
6030,Constructive Criticism,English,7,2025-07-28T16:36:14Z,Positive,Genuine feedback,"I like the suit Obinna is wearing. Well, the c..."

In [49]:
loader.clean_language_column()

✅ Cleaned 'language' column.

,category,language,likes,published_at,sentiment,subcategory,text
0,Irony/Sarcasm,Code Switching,10,2025-07-28T16:36:04Z,Positive,Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...
1,Others,Sheng,0,2025-07-28T16:35:44Z,Neutral,General Others,rada zako wasingam
2,Constructive Criticism,Sheng,0,2025-07-28T16:35:12Z,Positive,Genuine Praise,Izo chwom mbaya ndio zetuu😂😂
3,Constructive Criticism,Code Switching,0,2025-07-28T16:35:07Z,Positive,Genuine Praise,Nka shy😅
4,Constructive Criticism,Sheng,1,2025-07-28T16:34:43Z,Neutral,Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka
...,...,...,...,...,...,...,...
6026,Irony/Sarcasm,Sheng,0,2025-07-28T16:38:05Z,Negative,Mock compliment,Wenye hawajui venye street hu-run mnafloat tu😂...
6027,Constructive Criticism,English,0,2025-07-28T16:37:50Z,Positive,Genuine feedback,I can answer that question more further😂😂😂😂😂😂
6028,Constructive Criticism,English,2,2025-07-28T16:37:39Z,Positive,Genuine Praise,wedding of the year ❤❤
6029,Constructive Criticism,Sheng,1,2025-07-28T16:37:19Z,Neutral,Supportive Speech,"Hiyo wedding nayo , episode 2000 and I can’t g..."
6030,Constructive Criticism,English,7,2025-07-28T16:36:14Z,Positive,Genuine feedback,"I like the suit Obinna is wearing. Well, the c..."

# 📊 Exploratory Data Analysis (EDA)

## Introduction

This section explores the structure, distribution, and characteristics of the cyberbullying dataset before modeling.  
The goal is to understand patterns in categories, sentiment, text behavior, language usage, and posting activity.

In [50]:
eda = EDA(loader.data)

### A) Dataset Overview

The dataset overview examined the structure and quality of the data.  
This included checking the number of rows and columns, data types, column names, and missing values.  

This step ensured the dataset is clean, properly formatted, and ready for deeper exploratory analysis and modeling.

In [51]:

eda.dataset_overview()

📊 DATASET OVERVIEW
============================================================
Shape: (6011, 7)

Columns:
['category', 'language', 'likes', 'published_at', 'sentiment', 'subcategory', 'text']

Data Types:
category        object
language        object
likes            int64
published_at    object
sentiment       object
subcategory     object
text            object
dtype: object

Missing Values:
category        0
language        0
likes           0
published_at    0
sentiment       0
subcategory     0
text            0
dtype: int64

### B) Target Distribution Analysis

This analysis explored the distribution of posts across different cyberbullying categories and sentiment classes.  

Understanding class balance is important for machine learning, as imbalanced data may require resampling or class weighting.  
The sentiment distribution also provides insight into the overall emotional tone of the dataset.

In [52]:
eda.target_distribution("category")

Class Percentages:
category
Constructive Criticism    52.74
Others                    21.73
Cyberbullying             10.66
Irony/Sarcasm              8.53
Offensive                  4.62
Misinformation             1.10
Hate Speech                0.62
Name: proportion, dtype: float64

In [53]:
eda.target_distribution("sentiment")

Class Percentages:
sentiment
Neutral     38.20
Positive    33.72
Negative    28.08
Name: proportion, dtype: float64

### C) Subcategory Analysis

The subcategory analysis examined more detailed classifications of cyberbullying behavior.  

This helps identify dominant bullying patterns and determines whether fine-grained classification is feasible.  
It also highlights subcategories that may require balancing during model training.

In [54]:
eda.subcategory_analysis()

### D) Text Length Analysis

Text length analysis evaluated the distribution of post lengths in characters.  

This insight helps determine appropriate tokenization limits, sequence lengths for NLP models, and detection of unusually short or long posts that may affect model performance.

In [55]:
eda.text_length_analysis()

Text Length Summary:
count    6011.000000
mean       49.085676
std        49.553109
min         1.000000
25%        21.000000
50%        36.000000
75%        61.000000
max      1020.000000
Name: text_length, dtype: float64

### E) Language Distribution

The language distribution analysis identified the dominant languages used in the dataset.  

This is important for preprocessing decisions such as stopword removal, tokenization strategy, and determining whether multilingual modeling is required.

In [56]:
eda.language_insights()

Language Percentages:
language
Code Switching    38.58
English           24.07
Sheng             18.28
Swahili           16.54
Plain Emoji        2.53
Name: proportion, dtype: float64

### F) Peak Posting Time Analysis (Kenyan Time - EAT)

This analysis converted timestamps to Kenyan time (EAT - UTC+3) and examined hourly posting patterns.  

Identifying peak activity hours provides behavioral insights into when cyberbullying is most active and may support real-time moderation strategies.  
Weekend and weekday comparisons further contextualize user behavior.

In [57]:
eda.peak_posting_times("published_at")

🕒 Posting Activity by Hour
============================================================
hour
0     478
1     179
2     100
3      77
4      63
5      48
6      62
7     100
8     186
9     218
10    230
11    289
12    281
13    307
14    225
15    219
16    237
17    218
18    222
19    365
20    454
21    490
22    396
23    567
Name: count, dtype: int64

🔥 Peak Posting Hour:
23:00

📅 Weekend vs Weekday Activity
============================================================
is_weekend
False    4228
True     1783
Name: hour, dtype: int64

hour
0     478
1     179
2     100
3      77
4      63
5      48
6      62
7     100
8     186
9     218
10    230
11    289
12    281
13    307
14    225
15    219
16    237
17    218
18    222
19    365
20    454
21    490
22    396
23    567
Name: count, dtype: int64

### G) Key Findings Summary

The key findings section summarized major insights from the EDA process, including dominant categories, sentiment trends, language patterns, and average text length.  

These insights guide preprocessing decisions, feature engineering, and model development strategies for the cyberbullying detection system.

In [58]:
eda.key_findings()

🔎 KEY FINDINGS SUMMARY
============================================================
Total Samples: 6011

Top Category:
Constructive Criticism

Top Sentiment:
Neutral

Most Common Language:
Code Switching

Average Text Length: 49.09 characters

## PRE-PROCESSING

In [59]:
from Data_prep.preprocesssing import TextPreprocessor
preprocessor = TextPreprocessor()
final_df = preprocessor.transform(data, column="text")
final_df.head()

,category,language,likes,published_at,sentiment,subcategory,text,clean_text
0,Irony/Sarcasm,Code Switching,10,2025-07-28T16:36:04Z,Positive,Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...,napenda hii couple but hapo kwa 29yrs nimekata...
1,Others,Sheng,0,2025-07-28T16:35:44Z,Neutral,General Others,rada zako wasingam,rada zako wasingam
2,Constructive Criticism,Sheng,0,2025-07-28T16:35:12Z,Positive,Genuine Praise,Izo chwom mbaya ndio zetuu😂😂,izo chwom mbaya ndio zetuu face_with_tears_of_...
3,Constructive Criticism,Code Switching,0,2025-07-28T16:35:07Z,Positive,Genuine Praise,Nka shy😅,nka shy grinning_face_with_sweat
4,Constructive Criticism,Sheng,1,2025-07-28T16:34:43Z,Neutral,Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka,ata kama ni dooh kuna shida zingine siwezi taka

## Feature Engineering

In [60]:
from Models.Feature_engineering import FeatureEngineer

fe = FeatureEngineer()

X_train_text, X_test_text, y_train, y_test = fe.split(
    final_df["clean_text"],
    final_df["language"]
)

X_train = fe.fit_transform(X_train_text)
X_test = fe.transform(X_test_text)

# MODELLING

## LANGUAGE CLASSIFIER

In [61]:
def curate_language(label):

    if label == "English":
        return "English"

    elif label == "Swahili":
        return "Swahili"

    elif label in ["Sheng", "Code Switching"]:
        return "Kenyan_slang"

    elif label == "Plain Emoji":
        return "Emoji"

    else:
        return label

final_df["language"] = final_df["language"].apply(curate_language)

In [62]:
final_df["language"].value_counts()

language
Kenyan_slang    3418
English         1447
Swahili          994
Emoji            152
Name: count, dtype: int64

In [63]:
final_df

,category,language,likes,published_at,sentiment,subcategory,text,clean_text
0,Irony/Sarcasm,Kenyan_slang,10,2025-07-28T16:36:04Z,Positive,Hyperbolic understatement,Napenda hii couple but hapo kwa 29yrs nimekata...,napenda hii couple but hapo kwa 29yrs nimekata...
1,Others,Kenyan_slang,0,2025-07-28T16:35:44Z,Neutral,General Others,rada zako wasingam,rada zako wasingam
2,Constructive Criticism,Kenyan_slang,0,2025-07-28T16:35:12Z,Positive,Genuine Praise,Izo chwom mbaya ndio zetuu😂😂,izo chwom mbaya ndio zetuu face_with_tears_of_...
3,Constructive Criticism,Kenyan_slang,0,2025-07-28T16:35:07Z,Positive,Genuine Praise,Nka shy😅,nka shy grinning_face_with_sweat
4,Constructive Criticism,Kenyan_slang,1,2025-07-28T16:34:43Z,Neutral,Decision-criticism,Ata kama ni dooh kuna shida zingine siwezi taka,ata kama ni dooh kuna shida zingine siwezi taka
...,...,...,...,...,...,...,...,...
6026,Irony/Sarcasm,Kenyan_slang,0,2025-07-28T16:38:05Z,Negative,Mock compliment,Wenye hawajui venye street hu-run mnafloat tu😂...,wenye hawajui venye street hu-run mnafloat tu ...
6027,Constructive Criticism,English,0,2025-07-28T16:37:50Z,Positive,Genuine feedback,I can answer that question more further😂😂😂😂😂😂,i can answer that question more further face_w...
6028,Constructive Criticism,English,2,2025-07-28T16:37:39Z,Positive,Genuine Praise,wedding of the year ❤❤,wedding of the year red_heart red_heart
6029,Constructive Criticism,Kenyan_slang,1,2025-07-28T16:37:19Z,Neutral,Supportive Speech,"Hiyo wedding nayo , episode 2000 and I can’t g...","hiyo wedding nayo , episode 2000 and i cant ge..."
6030,Constructive Criticism,English,7,2025-07-28T16:36:14Z,Positive,Genuine feedback,"I like the suit Obinna is wearing. Well, the c...","i like the suit <person> is wearing. well, the..."

In [64]:
from Models.language_classifier import LanguageClassifier

texts = final_df["clean_text"]
labels = final_df["language"]

lang_model = LanguageClassifier()

lang_model.train(texts, labels)

Classification Report

              precision    recall  f1-score   support

       Emoji       0.51      0.83      0.63        30
     English       0.69      0.69      0.69       290
Kenyan_slang       0.73      0.74      0.74       684
     Swahili       0.41      0.36      0.38       199

    accuracy                           0.67      1203
   macro avg       0.59      0.65      0.61      1203
weighted avg       0.66      0.67      0.66      1203


Macro F1: 0.6099089107900303
Weighted F1: 0.6636707118017261

Confusion Matrix

[[ 25   2   3   0]
 [  9 200  72   9]
 [ 12  73 506  93]
 [  3  16 109  71]]

In [65]:
lang_model.save("language_model.pkl")

## Sentiment Modelling

In [66]:
texts = final_df["clean_text"]
labels = final_df["sentiment"]

In [67]:
from Models.sentiment_classifier import SentimentClassifier

texts = final_df["clean_text"]
labels = final_df["sentiment"]

sentiment_model = SentimentClassifier()

sentiment_model.train(texts, labels)

Classification Report

              precision    recall  f1-score   support

    Negative       0.51      0.63      0.56       338
     Neutral       0.48      0.42      0.45       459
    Positive       0.59      0.55      0.57       406

    accuracy                           0.52      1203
   macro avg       0.52      0.53      0.53      1203
weighted avg       0.52      0.52      0.52      1203


Macro F1: 0.5264283649808535
Weighted F1: 0.5211063461164954

Confusion Matrix

[[212  86  40]
 [148 193 118]
 [ 59 122 225]]

In [68]:
sentiment_model.save("sentiment_model.pkl")

## Category Modelling

In [69]:
from Models.category_classifier import CategoryClassifier

texts = final_df["clean_text"]
labels = final_df["category"]

category_model = CategoryClassifier()

category_model.train(texts, labels)

Classification Report

                        precision    recall  f1-score   support

Constructive Criticism       0.68      0.66      0.67       635
         Cyberbullying       0.27      0.25      0.26       128
           Hate Speech       1.00      0.14      0.25         7
         Irony/Sarcasm       0.26      0.39      0.31       103
        Misinformation       0.00      0.00      0.00        13
             Offensive       0.20      0.18      0.19        56
                Others       0.42      0.41      0.42       261

              accuracy                           0.51      1203
             macro avg       0.40      0.29      0.30      1203
          weighted avg       0.52      0.51      0.51      1203


Macro F1: 0.2995506419131674
Weighted F1: 0.5095378146041429

Confusion Matrix

[[420  47   0  60   3  14  91]
 [ 49  32   0  15   2  12  18]
 [  1   2   1   2   0   1   0]
 [ 23  11   0  40   0   2  27]
 [  6   1   0   2   0   1   3]
 [ 18  10   0   8   0  10  10]
 [ 98  16   0  28   1  10 108]]

In [70]:
final_df['category'].value_counts()

category
Constructive Criticism    3170
Others                    1306
Cyberbullying              641
Irony/Sarcasm              513
Offensive                  278
Misinformation              66
Hate Speech                 37
Name: count, dtype: int64

In [71]:
def merge_category(label):

    if label in ["Hate Speech", "Misinformation"]:
        return "Harmful"

    elif label == "Constructive Criticism":
        return "Constructive"

    elif label == "Irony/Sarcasm":
        return "Irony"

    else:
        return label


final_df["category"] = final_df["category"].apply(merge_category)

final_df["category"].value_counts()

category
Constructive     3170
Others           1306
Cyberbullying     641
Irony             513
Offensive         278
Harmful           103
Name: count, dtype: int64

## Modelling Using XLM-RoBERTa

In [72]:
final_df.to_csv('Category.csv')

In [73]:
final_df["subcategory"].value_counts()

subcategory
General Others                      1106
Supportive Speech                   1044
Genuine Praise                       568
Decision-criticism                   460
Genuine feedback                     431
Performance-based                    404
Mock compliment                      297
Corrective clarification             280
Direct Insult                        204
Humiliation                          196
General Inquiry                      166
Vulgar language (Matusi)             138
Mock Laughter                        109
Non-personal                         107
Defamation                            61
Body shaming                          59
Hyperbolic understatement             50
Rhetorical Question                   50
Threats                               45
Misleading/Contextual Deception       44
Trolling                              35
Gender based                          34
Spam                                  29
Sex-based                             25
Exclusion tactics                     24
Sexual harassment                     23
Ethical/racial group (Tribalism)      10
Political                              5
Fabricated Content (Fake News)         4
Disability                             2
Parody                                 1
Name: count, dtype: int64